### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by aryan-chanana** [pranavrawat1301/Text-Summarization-using-Seq2Seq#1]
Where is news_summary_more.csv file?

**Comment by pranavrawat1301** [comment]
I have added the link now as file was too large to be added , thanks for mentioning the oversight by me.

**Comment by aryan-chanana** [comment]
hi, I'm still unable to view the link, kindly share

**Comment by aryan-chanana** [comment]
Hey, I am stuck at this issue:

<generator object text_strip at 0x0000017BC7A94040>
<generator object text_strip at 0x000002E1D39F3AB0>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 129, in _main
    prepare(preparation_data)
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Ajay\Desktop\Text-Summarization-using-Seq2Seq-main\Text-Summarization-using-Seq2Seq-main\Text Summarization using seq2seq\text_summarization.py", line 86, in <module>
    text = [str(doc) for doc in nlp.pipe(brief_cleaning1, batch_size=5000, n_process=-1)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ajay\Desktop\Text-Summarization-using-Seq2Seq-main\Text-Summarization-using-Seq2Seq-main\Text Summarization using seq2seq\text_summarization.py", line 86, in <listcomp>
    text = [str(doc) for doc in nlp.pipe(brief_cleaning1, batch_size=5000, n_process=-1)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\language.py", line 1621, in pipe
    for doc in docs:
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\site-packages\spacy\language.py", line 1687, in _multiprocessing_pipe
    proc.start()
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__   
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 158, in get_preparation_data  
    _check_not_importing_main()
  File "C:\Users\Ajay\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by aryan-chanana** [comment]
![WhatsApp Image 2024-11-11 at 00 10 12](https://github.com/user-attachments/assets/d987ab1b-a2f2-407c-86bf-f0695ed08077)
It's been more than 8 hours... How long should i wait?

**Comment by pranavrawat1301** [comment]
Use some accelerator or GPU to do it faster , i personally used kaggle to speed up the process.
